require_paths:
- "C:/Program Files/SketchUp/SketchUp 2024/Tools"
- "C:/Program Files/SketchUp/SketchUp 2023/Tools"
- "C:/Program Files/SketchUp/SketchUp 2022/Tools"
- "C:/Program Files/SketchUp/SketchUp 2021/Tools"
- "C:/Program Files/SketchUp/SketchUp 2020/Tools"
- src

require:
- sketchup-api-stubs

reporters:
- rubocop
