name: RuboCop

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev/ci", "dev/ci-rubocop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  analysis:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7', '3.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: RuboCop version information
      run: bundle exec rubocop -V
    - name: Run RuboCop
      run: bundle exec rubocop
